version: '3.8'
services:
  postgres-server:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=#Y&g{zDs
      - POSTGRES_DB=postgres
      - TZ=America/Sao_Paulo
    volumes:
      - /postgresql/postgres/var/lib/postgresql/data:/var/lib/postgresql/data
    restart: unless-stopped
    ports: 
    - 5432:5432
    networks:
      zabbix-network:
networks:
  zabbix-network:
    driver: bridge