services:
  postgres-server:
    image: postgres:latest
    container_name: postgresql-zabbix
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=#Y&g{zDs
      - POSTGRES_DB=postgres
      - TZ=America/Sao_Paulo
    volumes:
      - /postgresql/postgres/var/lib/postgresql/data:/var/lib/postgresql/data
    restart: unless-stopped
    ports: 
      - 5432:5432
    networks:
      zabbix-network:

  zabbix-snmptraps:
    image: zabbix/zabbix-snmptraps:alpine-latest
    container_name: zabbix-snmptraps
    restart: unless-stopped
    ports:
      - 162:1162/udp
    volumes:
      - /zabbix/zabbix-snmptraps/zbx_instance/snmptraps:/var/lib/zabbix/snmptraps:rw
      - /zabbix/zabbix-snmptraps/var/lib/zabbix/mibs:/usr/share/snmp/mibs:ro
      - /zabbix/zabbix-snmptraps/var/lib/zabbix/mibs:/var/lib/zabbix/mibs
    networks:
      zabbix-network:
    depends_on:
      - postgres-server

  zabbix-server-pgsql:
    image: zabbix/zabbix-server-pgsql:alpine-latest
    container_name: zabbix-server-pgsql
    environment:
      - DB_SERVER_HOST=postgresql-zabbix
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=#Y&g{zDs
      - POSTGRES_DB=postgres
      - ZBX_ENABLE_SNMP_TRAPS=true
      - ZBX_CACHESIZE=1G
      - ZBX_STARTDBSYNCERS=10
      - ZBX_HISTORYCACHESIZE=1G
      - ZBX_TRENDCACHESIZE=512M
      - ZBX_VALUECACHESIZE=512M
      - ZBX_STARTPOLLERS=50
      - ZBX_STARTPREPROCESSORS=10
      - ZBX_STARTPOLLERSUNREACHABLE=25
      - ZBX_STARTPINGERS=25
      - ZBX_STARTDISCOVERERS=5
      - ZBX_STARTHTTPPOLLERS=25
      - ZBX_STARTTIMERS=15
      - ZBX_HOUSEKEEPINGFREQUENCY=12
      - ZBX_MAXHOUSEKEEPERDELETE=1000
      - ZBX_TIMEOUT=30
      - ZBX_UNREACHABLEPERIOD=45
      - ZBX_UNAVAILABLEDELAY=60
      - ZBX_UNREACHABLEDELAY=15
      - ZBX_LOGSLOWQUERIES=3000
      - ZBX_STARTPROXYPOLLERS=10
      - ZBX_STATSALLOWEDIP=127.0.0.1
    restart: unless-stopped
    ports:
      - 10051:10051
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /zabbix-server-pgsql/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
      - /zabbix-server-pgsql/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - /zabbix-server-pgsql/var/lib/zabbix/export:/var/lib/zabbix/export:rw
      - /zabbix-server-pgsql/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - /zabbix-server-pgsql/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - /zabbix-server-pgsql/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - /zabbix-server-pgsql/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
      - /zabbix-server-pgsql/var/lib/zabbix/ssl/certs:/var/lib/zabbix/ssl/certs
      - /zabbix-server-pgsql/var/lib/zabbix/ssl/keys:/var/lib/zabbix/ssl/keys
      - /zabbix-server-pgsql/var/lib/zabbix/ssl/ssl_ca:/var/lib/zabbix/ssl/ssl_ca
      - /zabbix-snmptraps/zbx_instance/snmptraps:/var/lib/zabbix/snmptraps:rw
      - /zabbix-snmptraps/var/lib/zabbix/mibs:/usr/share/snmp/mibs:ro
    networks:
      zabbix-network:
    depends_on:
      - postgres-server

  zabbix-web-nginx-pgsql:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-latest
    container_name: zabbix-web-nginx-pgsql
    restart: unless-stopped
    ports:
      - 443:8443
      - 80:8080
    environment:
      - PHP_TZ=America/Sao_Paulo
      - ZBX_SERVER_NAME=Intelli-ZBBX
      - ZBX_SERVER_HOST=zabbix-server-pgsql
      - DB_SERVER_HOST=postgresql-zabbix
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=#Y&g{zDs
      - POSTGRES_DB=postgres
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /zabbix-web-nginx/etc/ssl/nginx:/etc/ssl/nginx:ro
      - /zabbix-web-nginx/usr/share/zabbix/modules:/usr/share/zabbix/modules
    networks:
      zabbix-network:
    depends_on:
      - postgres-server
      - zabbix-server-pgsql

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    container_name: zabbix-agent
    restart: unless-stopped
    ports:
      - 10050:10050
    environment:
      - ZBX_SERVER_HOST=zabbix-server-pgsql
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_LOGREMOTECOMMANDS=1
    volumes:
      - /zabbix-agent/var/lib/zabbix/enc:/var/lib/zabbix/enc
      - /zabbix-agent/var/lib/zabbix/modules:/var/lib/zabbix/modules
      - /zabbix-agent/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d
    networks:
      zabbix-network:
    depends_on:
      - zabbix-server-pgsql

networks:
  zabbix-network:
    driver: bridge
